sonar.projectKey=banco-java-puro
sonar.projectName=Sistema Bancario Java
sonar.projectVersion=1.0

# Credenciales por defecto
sonar.login=squ_cfa8fccc6fe968fb8465b5816f57595c7b19b725
# sonar.password=1Dawrpp1708?

# Rutas del proyecto
sonar.sources=src/main
sonar.tests=src/tests
sonar.java.binaries=bin
sonar.coverage.jacoco.xmlReportPaths=reportes/jacoco.xml
